# Meta Data for SEO

## Homepage
title = "MedAlign"
titleSeparator = ":"
titleAddition = "A Clinician-Generated Dataset for Instruction Following with Electronic Medical Records"
description = "MedAlign is a benchmark dataset of natural language instructions for evaluating large language models on instruction following tasks grounded in the Electronic Medical Record."

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "doks.netlify.app"
titleHome = "MedAlign Project Website"

## Twitter Cards
twitterSite = "@drnigam"
twitterCreator = "@_scott_fleming_"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Doks"
schemaAuthor = "Henk Verlinde"
schemaAuthorTwitter = "https://twitter.com/_scott_fleming_"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/thescottfleming/"
schemaAuthorGitHub = "https://github.com/scottfleming"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/som-shahlab/medalign"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022-2023 Scott Fleming"

# Alert
alert = false
alertText = "Like MedAlign? <a class=\"alert-link\" href=\"https://github.com/som-shahlab/medalign\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/som-shahlab/medalign-website"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  collapsibleSidebar = false